// {
//   "total": 2,
//   "kwd": "",
//   "pageNum": 1,
//   "pageSize": 10,
//   "category": "",
//   "sort": "",
//   "result": [
//   {
//     "titleInfo": "광고, 쉽게 알 수 있는 사전",
//     "typeName": "도서",
//     "placeInfo": "4층 도서자료실(서고자료대출반납)",
//     "authorInfo": "[塚本輝雄 편저];이원형 편역",
//     "pubInfo": "커뮤니케이션북스",
//     "menuName": "오프라인자료",
//     "mediaName": "인쇄자료(책자형)",
//     "manageName": "본관",
//     "pubYearInfo": "2005",
//     "controlNo": "KMO200618720",
//     "docYn": "LD_VIEWER",
//     "orgLink": "이용불가",
//     "id": "60537310",
//     "typeCode": "B1",
//     "licYn": "L",
//     "licText": "[국립중앙도서관]-무료",
//     "regDate": "20060614",
//     "detailLink": "/NL/contents/search.do#viewKey=60537310&viewType=AH1",
//     "isbn": "8984993727",
//     "callNo": "326.14-6-25",
//     "kdcCode1s": "3",
//     "kdcName1s": "사회과학",
//     "classNo": "326.14",
//     "imageUrl": "kolis/2006/KMO200618720_thumbnail.jpg"
//   },
//   {
//     "titleInfo": "광고 쉽게 알 수 있는 사전",
//     "typeName": "도서",
//     "placeInfo": "디지털도서관 디지털자료실",
//     "authorInfo": "쓰카모토 데루오 이원형",
//     "pubInfo": "커뮤니케이션북스",
//     "menuName": "온라인자료",
//     "mediaName": "",
//     "manageName": "디지털도서관",
//     "pubYearInfo": "20051230",
//     "controlNo": "KMO200618720",
//     "docYn": "LD_VIEWER",
//     "orgLink": "이용불가",
//     "id": "0000000105533261",
//     "typeCode": "D1",
//     "licYn": "L",
//     "licText": "[국립중앙도서관]-무료",
//     "regDate": "20151120",
//     "detailLink": "/NL/contents/search.do#viewKey=CNTS-00071034337&viewType=C",
//     "isbn": "8984993727",
//     "callNo": "",
//     "kdcCode1s": "3",
//     "kdcName1s": "사회과학",
//     "classNo": "",
//     "imageUrl": "kolis_on/2015/CNTS-00071034337_thumbnail.jpg"
//   }
// ]
// }
